export const UPDATE_DDM_VISIBILITY = 'UPDATE_DDM_VISIBILITY'
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const UPDATE_WINDOW_WIDTH = 'UPDATE_WINDOW_WIDTH'
export const UPDATE_BOOKING = 'UPDATE_BOOKING'
